{{- if and .Values.benchmarkDeployments.serviceAccount.create (ne .Values.benchmarkDeployments.serviceAccount.name "default")}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.benchmarkDeployments.serviceAccount.name }}
  labels:
    {{- include "minigun.labels" . | nindent 4 }}
  {{- with .Values.benchmarkDeployments.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.benchmarkDeployments.serviceAccount.automount }}
{{- end }}
