{
 "title": "Kubernetes: Minigun HTTP Benchmark",
 "description": "Metrics from Minigun HTTP Benchmark tool.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(minigun_config_workers,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(minigun_config_workers{cluster=\"$cluster\"}, namespace) "
    }
   },
   {
    "name": "name",
    "label": "Benchmark name",
    "query": {
     "query": "label_values(minigun_config_workers{cluster=\"$cluster\",namespace=~\"^$namespace$\"}, name) "
    }
   },
   {
    "name": "instance",
    "label": "Benchmark test instance",
    "query": {
     "query": "label_values(minigun_config_workers{cluster=\"$cluster\",namespace=~\"^$namespace$\",name=~\"$name\"}, instance) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall per benchmark name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(minigun_requests_total{cluster=\"$cluster\", namespace=~\"^$namespace$\", name=\"$name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(minigun_requests_success_total{cluster=\"$cluster\", namespace=~\"^$namespace$\", name=\"$name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(minigun_requests_errors_total{cluster=\"$cluster\", namespace=~\"^$namespace$\", name=\"$name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Main Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (irate (minigun_requests_bytes_sum{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (instance)",
     "legendFormat": "Out {{instance}}"
    },
    {
     "expr": "-sum (irate (minigun_response_bytes_sum{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (instance)",
     "legendFormat": "In  {{instance}}"
    },
    { "expr": "vector(0)", "legendFormat": "zero" }
   ]
  },
  {
   "title": "Connections rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(minigun_httptrace_connect_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(minigun_requests_total{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (instance), 0.001)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Response Volume by Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(minigun_response_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (instance, status), 0.001)",
     "legendFormat": "{{ instance }}, Status:{{ status }}"
    }
   ]
  },
  {
   "title": "Request Errors Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(minigun_requests_errors_total{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (instance), 0.001)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Request Success Percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(minigun_requests_success_total{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])/irate(minigun_requests_total{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Full request time",
   "type": "timeseries",
   "description": "Full time of every request starting from the beginning (DNS query) and ending with receiving full response.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(minigun_requests_duration_seconds_sum{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name) /\navg(irate(minigun_requests_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name)",
     "legendFormat": "Mean:"
    },
    {
     "expr": "avg(minigun_requests_duration_seconds{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}) by (name, quantile)",
     "legendFormat": "{{quantile}}:"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "description": "Time since request headers and body are sent and until the full response received.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(minigun_response_duration_seconds_sum{cluster=\"$cluster\",status=\"200\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name) /\navg(irate(minigun_response_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name)",
     "legendFormat": "Mean:"
    },
    {
     "expr": "avg(minigun_response_duration_seconds{cluster=\"$cluster\",status=\"200\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}) by (name, quantile)",
     "legendFormat": "{{quantile}}:"
    }
   ]
  },
  {
   "title": "DNS, TCP and TLS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS query rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(minigun_httptrace_dns_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DNS query duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(minigun_httptrace_dns_duration_seconds_sum{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name) /\navg(irate(minigun_httptrace_dns_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name)",
     "legendFormat": "Mean:"
    },
    {
     "expr": "avg(minigun_httptrace_dns_duration_seconds{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}) by (name, quantile)",
     "legendFormat": "{{quantile}}:"
    }
   ]
  },
  {
   "title": "TCP connect rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(minigun_httptrace_connect_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "TCP connect time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(minigun_httptrace_connect_duration_seconds_sum{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name) /\navg(irate(minigun_httptrace_connect_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name)",
     "legendFormat": "Mean:"
    },
    {
     "expr": "avg(minigun_httptrace_connect_duration_seconds{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}) by (name, quantile)",
     "legendFormat": "{{quantile}}:"
    }
   ]
  },
  {
   "title": "TLS handshake rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(minigun_httptrace_tls_handshake_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "TLS handshake time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(minigun_httptrace_tls_handshake_duration_seconds_sum{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name) /\navg(irate(minigun_httptrace_tls_handshake_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name)",
     "legendFormat": "Mean:"
    },
    {
     "expr": "avg(minigun_httptrace_tls_handshake_duration_seconds{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}) by (name, quantile)",
     "legendFormat": "{{quantile}}:"
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Write request body duration",
   "type": "timeseries",
   "description": "Time required to write request body to the remote endpoint.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(minigun_httptrace_write_request_body_duration_seconds_sum{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name) /\navg(irate(minigun_httptrace_write_request_body_duration_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name)",
     "legendFormat": "Mean:"
    },
    {
     "expr": "avg(minigun_httptrace_write_request_body_duration_seconds{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}) by (name, quantile)",
     "legendFormat": "{{quantile}}:"
    }
   ]
  },
  {
   "title": "Time to first byte",
   "type": "timeseries",
   "description": "Time from the beginning of request till the first byte of response is received.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(minigun_httptrace_time_to_first_byte_seconds_sum{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name) /\navg(irate(minigun_httptrace_time_to_first_byte_seconds_count{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}[5m])) by (name)",
     "legendFormat": "Mean:"
    },
    {
     "expr": "avg(minigun_httptrace_time_to_first_byte_seconds{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=~\"$name\"}) by (name, quantile)",
     "legendFormat": "{{quantile}}:"
    }
   ]
  },
  {
   "title": "Benchmark Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Task queue length",
   "type": "timeseries",
   "description": "The length of the tasks queue in Minigun benchmark tool.\n\nIdeally this should be zero all the time. If you get constant high value here, then it means Minigun worker(s) can't run HTTP requests at the desired rate which could be caused by the target endpoint slowness or by the lack of Minigun resources/workers. Try increasing the workers count in your Minigun benchmark and make sure they have enough CPU.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minigun_runtime_channel_length{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=\"$name\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\",namespace=~\"^$namespace$\",container=\"minigun\",pod=~\"^$instance$\"}) by (container)",
     "legendFormat": "Limit ({{ container }})"
    },
    {
     "expr": "sum by (pod)( rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=~\"^$namespace$\",image!=\"\",container=\"minigun\",container!=\"POD\",pod=~\"^$instance$\"}[5m] ) )",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Task queue full events",
   "type": "timeseries",
   "description": "The number of task queue full events.\n\nIdeally this should be zero all the time. If you get constant high value here, then it means Minigun worker(s) can't run HTTP requests at the desired rate which could be caused by the target endpoint slowness or by the lack of Minigun resources/workers. Try increasing the workers count in your Minigun benchmark and make sure they have enough CPU.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(minigun_runtime_channel_full_events{cluster=\"$cluster\",namespace=~\"^$namespace$\",instance=~\"^$instance$\",name=\"$name\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU throttle rate",
   "type": "timeseries",
   "description": "This should be 0% all the time. If it's not, it means Minigun workers are throttled and benchmark result will be affected by it.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pod)(rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\",image!=\"\",container=\"minigun\",namespace=~\"^$namespace$\",pod=~\"^$instance$\"}[5m] )) / avg by (pod)(rate(container_cpu_cfs_periods_total{cluster=\"$cluster\",image!=\"\",container=\"minigun\",namespace=~\"^$namespace$\",pod=~\"^$instance$\"}[5m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}